---
###
- hosts: localhost
  tasks:
    - name: test connection
      ping:

    - name: install tree command using brew 
      homebrew: name=tree state=present

    - name: sleep 1 min 
      command: sleep 60
